---
- hosts: toils
  vars:
    application_name: toils
    image_dir: /srv/qemu
  tasks:
    - name: Create directory to store VM images
      become: yes
      file:
        path: "{{ image_dir }}"
        state: directory
        mode: "0700"

    - name: OS and Storage images
      become: yes
      copy:
        src: "{{ item }}"
        dest: "{{ image_dir }}/"
        mode: "0700"
        force: no
        setype: virt_image_t
      with_items:
        - "../toils-os.qcow2"
        - "../toils-storage.qcow2"

    - name: App image
      become: yes
      copy:
        src: "../toils-app.img"
        dest: "{{ image_dir }}"
        mode: "0700"
        backup: yes
        setype: virt_image_t

    - name: Systemd service
      become: yes
      template:
        src: "templates/systemd-service.j2"
        dest: "/etc/systemd/system/toils.service"

    - name: Start systemd service
      become: yes
      systemd:
        daemon_reload: yes
        enabled: yes
        masked: no
        name: "{{ application_name }}"
        state: started

    # - name: Build production container image
    #   local_action:
    #     module: make
    #     chdir: "{{ playbook_dir }}/../"
    #     target: image

    # - name: Stop service
    #   systemd:
    #     scope: user
    #     name: "{{ application_name }}"
    #     state: stopped
